//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17351
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekConfAdmin
{


    public partial class EnumerationFilter
    {

        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
    }
}
