//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekConf
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_user
    {
        public long event_id { get; set; }
        public string user_id { get; set; }
        public string type { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual @event @event { get; set; }
    }
}
