//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekConf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_AspNetUsers
    {
        public long event_id { get; set; }
        public string user_id { get; set; }
        public string type { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Event Event { get; set; }
    }
}
